name: b_go
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.12.3
  flutter_facebook_auth: ^7.1.2
  elevated_ticket_widget: ^0.0.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  intl: ^0.18.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.4.2
  esc_pos_utils: ^1.1.0 # ✅ Use original package
  esc_pos_printer: ^4.1.0
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/bus_red.png
    - assets/bus_blue.png
    - assets/bus_green.png
    - assets/bus_yellow.png
    - assets/bus_purple.png
    - assets/bus_orange.png
    - assets/bus.png
    - assets/bus2.png
    - assets/ticket.png
    - assets/gps.png
    - assets/bus-stop.png
    - assets/highway-sign.png
    - assets/bag.png
    - assets/passenger.png
    - assets/signal.png
    - assets/work.png
    - assets/batrasco-logo.png
    - assets/google-icon.png
    - assets/facebook-icon.png
    - assets/sos-button.png
    - assets/photo-camera.png
    - assets/phone-call.png
    - assets/batrasco_bus.jpg
    - assets/payment-qr.jpg
