// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjqLNklma1gr3IOwPxiMO5S38hu8UQ2Fc',
    appId: '1:183068104612:web:beb560880f035631265331',
    messagingSenderId: '183068104612',
    projectId: 'it-capstone-6fe19',
    authDomain: 'it-capstone-6fe19.firebaseapp.com',
    storageBucket: 'it-capstone-6fe19.appspot.com', // fixed domain
    measurementId: 'G-F56ZXEN0FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuZHCcRdGvMyxxPhV4R8YcOUuRDH6yCXA',
    appId: '1:183068104612:android:7f42637f006a2739265331',
    messagingSenderId: '183068104612',
    projectId: 'it-capstone-6fe19',
    storageBucket: 'it-capstone-6fe19.appspot.com', // fixed domain
  );
}
